### PR TITLE
Linux project files and fixes.

### PR DESCRIPTION
**Pull request by PetrosKataras**
All examples work from an initial test on Linux except SkeletalAnimation which crashes during load ( but I suspect this example might not be up-to-date with recent changes? )

### CODE REVIEW

**Comment by ryanbartley** [comment]
Hey @PetrosKataras, thanks so much! I'll take a look at Skeletal animation now.

**Comment by ryanbartley** [comment]
@PetrosKataras, I just ran the skeletal animation and it ran fine. Did your rename of the gltf files fix it, or is there still something wrong?

**Comment by PetrosKataras** [comment]
Hey Ryan, the file name fixes allow for finding the assets but there is still something wrong cause its throwing an exception of type `cinder::StreamExc`  . Not much time right now to debug it properly though so I will have to come back to this later on.

**Comment by ryanbartley** [comment]
No problem. I'll also look into it tonight.

## 

Ryan Bartley
214-641-7788

**Pull request merged**
